- src/spetlr/etl/extractors/incremental_extractor.py
- tests/cluster/etl/test_incremental_extractor.py
This PR will fix so overlapping periods in incremental extractors works correctly when the target table is empty.
> fix overlap period with empty target

- src/spetlr/delta/delta_handle.py
Fix issue in delta merge sql execution.
When doing delta merge within a streaming context, the temp view of the source dataframe can't be found.
Therefore the merge sql statement have to be run from a spark context on the dataframe.
This also works for normal batch merge.
> fix: fix-delta-merge-when-running-in-stream

- .pre-commit-config.yaml
- src/spetlr/sql/SqlServer.py
- src/spetlr/sql/SqlServerBaseOptions.py
The default options for SQL Server hardcode the driver versions. When updating the drivers, this needs to be configurable.
This PR makes it configurable.
> SqlServer Driver versions are now configurable

- docs/entry_points/README.md
- setup.cfg
- src/spetlr/entry_points/generalized_task_entry_point.py
Normally, to call code within a python wheel, an entry point must be specified in 
the `setup.cfg` file. To skip this part, spetlr provides a standard entry point, 
`spetlr_task`. Using this entry point, any other library code can be called.
If you want to call this function:
```python
def myfunction(myarg='default'): 
pass
```
that is residing in the file `mylib.myfolder.myfile`,
then specify your task as follows:
```json
{
"python_wheel_task": {
"package_name": "spetlr",
"entry_point": "spetlr_task",
"named_parameters": {
"entry_point": "mylib.myfolder.myfile:myfunction",
"myarg": "myval"
}
}
}
```
The `"package_name": "spetlr"` and  `"entry_point": "spetlr_task"` should always be 
kept. The mandatory parameter 'entry_point' then points to the code to be called 
[using standard …
> generalized entry points

- docs/utilities/README.md
- src/spetlr/configurator/configurator.py
- src/spetlr/exceptions/__init__.py
- src/spetlr/utils/CleanupTestDatabases.py
- src/spetlr/utils/__init__.py
- tests/cluster/delta/extras/tablenames.yml
- tests/cluster/delta/test_cleanup_databases.py
- tests/local/configurator/test_configurator.py
- tests/local/configurator/test_configurator_cli.py
- tests/local/utils/test_cleandatabases.py
This PR introduces methods for easily remove test tables from Databricks:
* CleanupTestDatabases
* Removes spark test databases
> feat: clean spark test databases

- docs/transformations/README.md
- src/spetlr/transformers/__init__.py
- src/spetlr/transformers/simple_dataframe_filter_transformer_nc.py
- tests/local/transformers/test_simple_dataframe_filter_transformer.py
- tests/local/transformers/test_simple_dataframe_filter_transformer_nc.py
Tranformer for making a simple filtering on one column for one value.
> feat: simple filter transformer nc

- docs/transformations/README.md
- src/spetlr/transformers/__init__.py
- src/spetlr/transformers/generate_md5_column_transformer_nc.py
- tests/local/transformers/test_generate_md5_column_transformer_nc.py
Create transformer for generating md5 encoded column based on other columns.
The transformer also handles if a value is NULL, by replacing it with empty string.
> Create transformer for generating md5 encoded column

- src/spetlr/configurator/_cli/generate_keys_file.py
I have seen cases were we created a file with backslashes in the name on mac. This made the repository impossible to check out in windows. This PR prevents that.
I tested the cli functionality by installing locally on my mac.
> better treatment of file paths

- src/spetlr/etl/loaders/UpsertLoader.py
- src/spetlr/etl/loaders/__init__.py
- src/spetlr/etl/loaders/load_modes.py
- src/spetlr/etl/loaders/simple_loader.py
- src/spetlr/etl/loaders/upsert_loader_streaming.py
- src/spetlr/orchestrators/eh2silver/EhToDeltaSilverOrchestrator.py
- tests/cluster/etl/test_simpleloader_upsert.py
- tests/cluster/etl/test_upsertloader.py
- tests/local/eh/test_ehtodeltasilver_orchestrator.py
- Refactor
- Feature
We use handlers in SPETLR. The handlers have already `.upsert()` - this means that the `SimpleLoader` can support an easy way of using upsert by providing `mode="upsert"`.
In the moment, the simpleloader only support "overwrite" and "append".
https://github.com/spetlr-org/spetlr/blob/main/src/spetlr/etl/loaders/simple_loader.py
The simpleloader now supports upserting.
#67 
IMO it would be very great to introduce even more upsert tests. But since we use the Spark SQL engine to execute the merge, we cannot unittests it as hoped.
> feat: add upsert to simpleloader

- src/spetlr/reporting/SlackNotifier.py
- tests/cluster/reporting/test_slack_reporting.py
- tests/local/reporting/test_slack_reporting.py
- Feature
The SlackNotifier class has a new method named "notify" which works similar to "notify_info" except that it does not show stack trace.
The SlackNotifier  class and its corresponding unit tests were modified.
The SlackNotifier class has a new method named "notify" which works similar to "notify_info" except that it does not show stack trace.
No. The current API can be used as it was.
> Add SlackNotifier with no stack trace

- src/spetlr/deltaspec/DeltaTableSpecBase.py
- tests/cluster/delta/deltaspec/tables.py
- tests/cluster/delta/deltaspec/test_tblspec.py
- Bug Fix
Managed tables actually have a location when described by spark. Blinding the DeltaTableSpec to managed locations makes the description match the create statement.
This fixes a bug where a managed table DeltaTableSpec did not compare equal to its named table after creation.
> ensure ability to control managed table

- src/spetlr/deltaspec/DeltaTableSpec.py
- src/spetlr/deltaspec/DeltaTableSpecBase.py
- src/spetlr/deltaspec/DeltaTableSpecDifference.py
- tests/cluster/delta/deltaspec/tables.py
- tests/cluster/delta/deltaspec/test_tblspec.py
- tests/local/delta/test_DeltaTableSpec.py
- Bug Fix
Previously the DeltaTableSpec default initalized the tableproperties to the values that are useful and necessary for column operations. This blinded it to the case that real tables may not have them. This new PR corrects this behavior. Now, only when we read the specification from SQL do we assume that the good values are desired. In all other cases we simply accept the given values.
In a way this makes a SQL initalized DeltaTableSpec more powerful than a default-initalized instance. Therefore the setting of the good defaults is exposed as a method available to the library user.
> Modify legacy tables.

- src/spetlr/configurator/sql/create.py
- src/spetlr/configurator/sql/view.py
- tests/local/configurator/test_configurator.py
- tests/local/configurator/views/view.sql
- Feature
The configurators ability to parse SQL statements is extended to include the ability to parse CREATE VIEW statements. 
For now, only the name can be extracted.
> allow configuration from view

- setup.cfg
- Optimization
Relaxing the version requirements for higher python versions should be ok since the limitation came from python 3.8 vs. numpy.
I am having versioning conflicts and this will hopefully help with that.
> try relaxing the version requirements

- src/spetlr/configurator/sql/StatementBlocks.py
- src/spetlr/configurator/sql/table.py
- src/spetlr/deltaspec/DeltaTableSpecDifference.py
- src/spetlr/schema_manager/spark_schema.py
- tests/local/delta/sql/tables.sql
- tests/local/delta/test_DeltaTableSpec.py
- Feature
- Support Generated and default expressions in sql parsing for detla table spec.
- Added a new `ignore()` method to the DeltaTableSpecDifference to simplify comparisons that focus on f.ex. schema.
> support generated and default expressions in schema

- src/spetlr/sql/SqlExecutor.py
- tests/local/sql/test_SqlExecutor.py
- Feature
The sql file execution in:
SqlExecutor(base_module).**execute_sql_file**(file_pattern)
should throw an exception if no .sql files are found in the base_module folder and the specified file_pattern. 
The reason for it is to detect spelling errors in the file or pattern name or choosing the wrong base_module folder by mistake.
if not found:
raise ValueError(f"No matching .sql files found in '{self.base_module}'")
No exception was thrown until now. The method did simply nothing.
A ValueError exception is thrown.
There is a potential breaking change if people relied on empty folders being ignored. There is a new parameter that will accomplish the same:
SqlExecutor(base_module, **ignore_empty_folder=True**).execute_sql_file(file_pattern)
> Throw an exception in SqlExecutor if no files found

- src/spetlr/etl/loaders/load_modes.py
- src/spetlr/etl/loaders/simple_loader.py
- tests/local/etl/test_simple_loader.py
- Feature
The option to overwriteSchema is not exposed int the simple loader.
> overwriteSchema in simple loader

- src/spetlr/azure_log_analytics/azure_log_analytics_handle.py
- src/spetlr/cosmos/cosmos_handle.py
- src/spetlr/sql/SqlExecutor.py
- src/spetlr/sql/sql_handle.py
- src/spetlr/tables/TableHandle.py
- tests/cluster/delta/test_sparkexecutor.py
- tests/cluster/delta/views/views.sql
- tests/cluster/transformations/test_union_transformer.py
- Feature
the replacements argument allows to reuse sql code multiple times with slightly changed replacements values. It is an oversight that it was not exposed on this method, since it *was* exposed on the `get_statements` method.
> expose the replacements argument

- setup.cfg
- Bug Fix
This micro-PR fixes an error where the latest PYPI version of `sqlparse` was causing errors with the Databricks ML Runtime 14.3, which uses a pinned `sqlparse==0.4.2`, whereas the version retrieved using `pip install sqlparse` is `sqlparse==0.4.4`.
Oddly, this caused an issue with `Lexer.get_default_instance`, a dependency when using`Configurator` from `spetlr`.
`spetlr` does not specify this version requirement, and hence it is added in this PR.
Pins `sqlparse>=0.4.4`.
´This is likely a common compatibility issue with the Databricks ML Runtime having around 300 python packages, all with pinned versions. If we do not follow their pinned version, `spetlr` may not necessarily be compatible with this runtime. On the other hand, these python package versions change with Databrick ML …
> Pinned sqlparse>=0.4.4 for Databricks ML Runtime 14.3 compatibility.

- docs/power_bi/README.md
- src/spetlr/power_bi/PowerBi.py
- src/spetlr/power_bi/__init__.py
- Feature
When calling the refresh() method it is now possible to specify the number of retries on transient errors.
No retries.
It is now possible to specify number or retries.
No
:param int number_of_retries: The number of retries on transient
errors when calling refresh(). Default is 0 (no retries).
(e.g. 1 means two attempts in total.)
Used only when the timeout_in_seconds parameter allows it!
> PowerBi - add retries on transient errors

- src/spetlr/power_bi/PowerBi.py
- tests/local/power_bi/test_power_bi.py
- Feature
The "timeout_in_seconds" parameter in the PowerBi constructor should be treated literally,
and the refresh() method should finish exactly at timeout.
The refresh() method waits max. 5 minutes between two PowerBI API requests,
which means the refresh() method could take up to 5 minutes longer after the timeout.
The refresh() method must finish exactly at timeout or earlier.
No
> feat: PowerBi refresh - more precise timeout handling

- src/spetlr/power_bi/PowerBi.py
- tests/local/power_bi/test_power_bi.py
- Bug Fix
When executing PowerBi.refresh(), use the previous completed refresh time regardless of a pending new refresh. This allows the refresh() method finish sooner.
The previous completed refresh time was overwritten when checking the pending refresh, so every sleep was 5 minutes.
The previous completed refresh time is now taken into consideration when executing sleep(), so the last sleep can be shorter (e.g. 60 seconds or 15 seconds) to match the previous refresh execution time.
No
> PowerBi.refresh() - use last completed refresh time

- docs/power_bi/README.md
- ruff.toml
- src/spetlr/power_bi/PowerBi.py
- tests/local/power_bi/test_power_bi.py
- Feature
It is now possible to refresh only selected tables in the dataset. This feature is optional.
There is a new parameter named "table_names", that can contain a list of tables to refresh within a dataset.
There is no such parameter, so all tables will be refreshed every time.
There is a new parameter named "table_names".
No
> feat: PowerBI-refresh-add-optional-table_names-parameter

- docs/power_bi/README.md
- src/spetlr/power_bi/PowerBi.py
- tests/local/power_bi/test_power_bi.py
What type of PR is this?
- Feature
Overview
The PowerBi refreshing logic has been extended with two new methods to show and get the refresh history list. The list is returned as a Spark data frame. Additionally, the last refresh time is calculated as an average of all previous refresh times via API (only those refreshing the entire dataset), to make the logic execute faster.
What is the current behavior?
There is no such feature.
Does this PR introduce a breaking change?
No, the logic is optional
> feat: PowerBI - get and show the refresh history list

- src/spetlr/delta/delta_handle.py
Streaming must read from the full table name, not from the name of the table within its DB
> stream from name

- src/spetlr/orchestrators/ehjson2delta/EhJsonToDeltaOrchestrator.py
- src/spetlr/orchestrators/ehjson2delta/EhJsonToDeltaTransformer.py
- tests/cluster/eh/test_eh_json_transformer.py
- Feature
The EhJsonToDeltaOrchestrator class should have a new optional parameter to disable case-sensitivity
when parsing JSON property names.
There is no parameter.
The EhJsonToDeltaOrchestrator class constructor has a new boolean parameter named "case_sensitive".
No
> Add the "case_sensitive" parameter to the EhJsonToDeltaOrchestrator

- docs/power_bi/README.md
- src/spetlr/power_bi/PowerBi.py
- Feature
The PowerBI class has a new parameter named "max_parallelism", specifying the maximum number of threads on which to run parallel processing commands during a PowerBI refresh.
No such parameter, which corresponds to 10 threads.
New parameter that can change the number of threads.
No
> Add the optional max_parallelism parameter to the PowerBi class

- docs/power_bi/README.md
- src/spetlr/power_bi/PowerBi.py
- Feature
Add four new optional parameters to the PowerBi() class constructor:
- apply_refresh_policy: bool = None,
- dataset_refresh_type: str = None,
- dataset_commit_mode: str = None,
- incremental_effective_date: str = None,
to control the PowerBI refresh logic.
The parameters are not available.
Four new optional parameters are available.
No.
> Add four new parameters to the power bi refresh logic

- src/spetlr/delta/delta_handle.py
- Bug Fix
Ensure backward compatibility for spetlr delta handle read()
table "path" is used when reading instead of table "name" if the name was not specified or it does not contain a dot.
Until the recent release, spetlr always used only "path". 
The previous release introduced a breaking change.
This release removes the breaking change.
No
> Ensure backward compatiblity for spetlr delta handle read

- docs/spark/README.md
- src/spetlr/spark.py
- src/spetlr/utils/DataframeCreator.py
- Feature
Add support for Databricks Connect.
No support
Support for Databricks Connect is added and can be enabled using an environment variable.
See the documentation in: docs/spark.README.md
No
> Add support for Databricks Connect

- docs/etl/README.md
- docs/spark/README.md
- src/spetlr/etl/loader.py
- src/spetlr/etl/transformer.py
- src/spetlr/spark.py
- tests/local/eh/test_ehtodeltabronze_orchestrator.py
- tests/local/etl/test_break_from_etl.py
- Feature
When either an extractor or transformer in an ETL flow returns None, and the following steps (i.e. transformer and loader) are simple steps taking only one data frame as input, the ETL flow will be stopped without triggering any errors, and the following steps will not be executed.
All steps are executed. Executing a transformer or loader that does not explicitly accept None as parameter will raise a null-reference exception.
If either the extractor or transformer returns None, the ETL flow will be stopped, provided the following steps are simple steps.
No.
> Allow breaking from the ETL flow

- src/spetlr/configurator/configurator.py
- tests/local/configurator/test_configurator_recursion.py
See the test in this PR.
The configurator erroneously identified a circular dependency because it reused the stack for each branch of the dependency resolution. This is fixed now.
> Recursion error in configurator

- src/spetlr/deltaspec/DeltaTableSpec.py
- src/spetlr/deltaspec/DeltaTableSpecBase.py
- tests/local/deltaspec/test_table_spec_from_sql.py
- tests/local/deltaspec/test_table_spec_helper_defs.py
- tests/local/deltaspec/test_table_spec_mkstgmatch.py
- tests/local/deltaspec/test_table_spec_uc_location.py
- Refactor
- (and more tests)
This PR introcues a handling of a unity catalog location for a table.
The location for the deltatablespec is actually external location - and unity catalog tables have no external location
Today, UC tables are not handled - the location is extracted, but it is a UC location - not external.
Simply by searching for ""__unitystorage/catalogs" in the location - we set it to None
If any have used the deltaspec, and use the extracted location as an actual location for access directly or such - it will break!
> feat: treat unity catalog location as none

- .pre-commit-config.yaml
- setup.cfg
- src/spetlr/configurator/configurator.py
- src/spetlr/exceptions/configurator_exceptions.py
- tests/local/configurator/test_configurator_recursion.py
- tests/local/configurator/test_configurator_threading.py
Closes #202
The Configurator was not thread safe and this caused issues.
- Separate all interface from all internal methods.
- sometimes it is necessary to split even simple methods into interface+internal.
- An interface method must take the lock and then never call another interface method.
- An internal method must not touch the lock, that is handled by interface methods.
- Internal methods must never call interface methods, only other internal methods.
- Only internal methods can recurse.
This guide allows us to guarantee that:
- all code that looks at internal data is behind a lock
- all interface methods take the lock.
- the lock is never taken twice, which would result in dead-lock.
This is a pure internal refacturing with no change in interface or functionality.
- Bug Fix
> Make configurator thread-safe

- setup.cfg
- src/spetlr/eh/EventHubStream.py
- src/spetlr/eh/EventhubStreamConnectionStringEncrypt.py
We used to have a call to a protected java method. This caused problems on Unity clusters where code protection features prevent this. I re-implemented the connection encryption in pure python to get the same result:
- I used standard crypto libraries for every sensitive transformation.
- There seems to be no library support for padding like in java, but the code seems so simple that I trust the code that I copied from online forums.
- I confirmed experimentally that the code works for me
> pure python connection string encryption

- src/spetlr/cache/CachedLoader.py
We ran into an issue where the write operations were few, but the delete operations were substantial, and were in error. The Cache Loader should limit the delete operations also in the same way as the write operations.
> Limit cached loader delete operations

- src/spetlr/delta/db_handle.py
- tests/local/delta/test_db_handle.py
- Refactor
This PR ensures that `dbhandle` can handle catalogs for database names.
Until now, database names was expected to have not dots in the name.
Due to three-level name space, a database/schema can be like this: catalog.database.
It is allowed to provide a dot in the database name - but only 1.
This only affect the validate step. It should not affect your current environment. But if you are used to, that the valdiation takes care of no dots in the name at all - you will have to ensure this in another way.
> feat: dbhandle handle catalog

- docs/power_bi/README.md
- src/spetlr/power_bi/PowerBi.py
- tests/local/power_bi/test_power_bi.py
- Feature
PowerBi class constructor has a new parameter "timeout_power_bi_in_seconds".
With the optional "timeout_power_bi_in_seconds" you can specify a
time-out in seconds inside PowerBI. If the time-out is exceeded,
PowerBI will interrupt refreshing and return a time-out error.
Additionally, the HTTP 400 Bad request exception is ignored for using DAX queries, if the user did not specifically ask for reading tables via DAX. Microsoft was still working for a solution at the time of making this PR:
https://community.fabric.microsoft.com/t5/Service/DAX-Info-Functions-Against-Published-Datasets/m-p/4374246
It is not possible to trigger a time-out in PowerBI.
An optional parameter has been added.
No. Default value for the new parameter is None.
> Add timeout_power_bi_in_seconds to PowerBi refresh

- src/spetlr/reporting/JobReflection.py
- src/spetlr/reporting/SlackNotifier.py
- Documentation Update
The SlackNotifier has issues using Shared Clusters access mode when UC is activated
This PR adds a comment for users.
> feat: add comment on UC access mode

- src/spetlr/delta/delta_handle.py
- src/spetlr/sql/SqlServer.py
- src/spetlr/transformations.py
- src/spetlr/utils/CheckDfMerge.py
- Optimization
There are data objects, such as the date "0001-01-01" which are valid spark values but fail when converting into python.
Using a take(1) to check if there are any rows makes us encounter this error, even though we did not care about the result of the conversion.
We could also just .count() with no limit but that could perhaps perform worse.
> Prevent collecting row to python

- src/spetlr/reporting/SlackNotifier.py
- tests/local/reporting/test_slack_reporting.py
- Optimization
When sending Slack messages the message header with the job name, the time and the message source is shown in one line instead of two lines.
Two separate header lines are shown.
One combined message header is shown.
No.
> Show Slack message headers in one line instead of two

- docs/eventhub/README.md
- src/spetlr/eh/__init__.py
- src/spetlr/eh/eventhub_handle.py
- src/spetlr/etl/transformers/__init__.py
- src/spetlr/etl/transformers/simple_eh_handle_write_transformer.py
- src/spetlr/exceptions/__init__.py
- tests/cluster/eh/test_eh_saving.py
- tests/cluster/eh/test_eventhub_handle.py
- tests/local/eh/test_eventhub_handle.py
- tests/local/transformers/test_simple_eh_handle_write_transformer.py
- (Refactor)
- Feature
This PR introduces an eventhubhandle
Currently, we have differenct eventhub related classes. Here among `eventhubstreamextractor`. which have been inspiration for some of the eventhandle code.
But, in our current setup, we do not provide a handle like the Delta and Sql. This PR introduces a full handle class for eventhub!
The `EventhubHandle` inherits all the TableHandle methods, and give the possibility to `.read()`, `.append()`, `.overwrite()`, `.read_stream()` and use the handle in the StreamLoader(handle=EventhubHandle) for microbatch stream writes.
> feat: eventhub handle using kafka
